### ISSUE TITLE
关于管理平台节点为空

### ISSUE THREAD

**Issue by a1most** [Autumn-27/ScopeSentry#10]
hello，我使用python运行管理平台，提示如下：
![image](https://github.com/Autumn-27/ScopeSentry/assets/34560797/282ae31c-2951-45c5-8b2e-ad9529309fcd)

然后节点我用exe进程直接运行，提示如下：
![image](https://github.com/Autumn-27/ScopeSentry/assets/34560797/42e19f83-58e7-4508-bcd9-b02c6499fda1)
现在问题是，我在节点管理里面能看到这个节点，但是在创建扫描任务时提示没有可用节点：
![image](https://github.com/Autumn-27/ScopeSentry/assets/34560797/ea54d934-0402-4c1c-bd3b-c3e9a68360d7)

**Comment by Autumn-27** [comment]
> hello，我使用python运行管理平台，提示如下： ![image](https://private-user-images.githubusercontent.com/34560797/339194846-282ae31c-2951-45c5-8b2e-ad9529309fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDgxNjYsIm5iZiI6MTcxODI0Nzg2NiwicGF0aCI6Ii8zNDU2MDc5Ny8zMzkxOTQ4NDYtMjgyYWUzMWMtMjk1MS00NWM1LThiMmUtYWQ5NTI5MzA5ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAzMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2Y2ZkOWVhYTU1ZjY4NDdmZjMyYzBlYjIwNGY0NDI0ZWFjMmFkYjU4NDMwYzE1YWIyOGUwNDJmNGVjMTYwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3eMhsvcVIKzGY7evTEeF3WnSVkYoM78Wvjmji73WDC0)
> 
> 然后节点我用exe进程直接运行，提示如下： ![image](https://private-user-images.githubusercontent.com/34560797/339195008-42e19f83-58e7-4508-bcd9-b02c6499fda1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDgxNjYsIm5iZiI6MTcxODI0Nzg2NiwicGF0aCI6Ii8zNDU2MDc5Ny8zMzkxOTUwMDgtNDJlMTlmODMtNThlNy00NTA4LWJjZDktYjAyYzY0OTlmZGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAzMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZDQ1NDEyODE1Zjg0NDVhNTc5NTlhNTc5M2Y0ZmEyNGE4OTAxZWFkOGEwNzEwOGUxMzk5Mzg3Mzg2Yjg2NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pUYb7if2WxxWQ_ySP_wqMt004SwPM-S0kiDJMsLtcMk) 现在问题是，我在节点管理里面能看到这个节点，但是在创建扫描任务时提示没有可用节点： ![image](https://private-user-images.githubusercontent.com/34560797/339195238-ea54d934-0402-4c1c-bd3b-c3e9a68360d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDgxNjYsIm5iZiI6MTcxODI0Nzg2NiwicGF0aCI6Ii8zNDU2MDc5Ny8zMzkxOTUyMzgtZWE1NGQ5MzQtMDQwMi00YzFjLWJkM2ItYzNlOWE2ODM2MGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAzMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZTA4ZWVjMGY3ZjFkOGM0NWQwNzc0NGE1MTgzNDcyZWVkY2Y4YTUxNWFjZmEzOWJmMDY4YmQwNTkwY2IzNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZVdMT7bsCgL8dIBXFfTE7TBXyjgAymZ4u20axSyAtw)

看起来是时区出了问题，可以看看系统配置是不是找不到这个时区，节点管理那里的更新时间为空，扫描节点会根据更新时间判断节点是否存活，所以就导致了节点为空的情况

**Comment by a1most** [comment]
> > hello，我使用python运行管理平台，提示如下： ![image](https://private-user-images.githubusercontent.com/34560797/339194846-282ae31c-2951-45c5-8b2e-ad9529309fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDgxNjYsIm5iZiI6MTcxODI0Nzg2NiwicGF0aCI6Ii8zNDU2MDc5Ny8zMzkxOTQ4NDYtMjgyYWUzMWMtMjk1MS00NWM1LThiMmUtYWQ5NTI5MzA5ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAzMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2Y2ZkOWVhYTU1ZjY4NDdmZjMyYzBlYjIwNGY0NDI0ZWFjMmFkYjU4NDMwYzE1YWIyOGUwNDJmNGVjMTYwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3eMhsvcVIKzGY7evTEeF3WnSVkYoM78Wvjmji73WDC0)
> > 然后节点我用exe进程直接运行，提示如下： ![image](https://private-user-images.githubusercontent.com/34560797/339195008-42e19f83-58e7-4508-bcd9-b02c6499fda1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDgxNjYsIm5iZiI6MTcxODI0Nzg2NiwicGF0aCI6Ii8zNDU2MDc5Ny8zMzkxOTUwMDgtNDJlMTlmODMtNThlNy00NTA4LWJjZDktYjAyYzY0OTlmZGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAzMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZDQ1NDEyODE1Zjg0NDVhNTc5NTlhNTc5M2Y0ZmEyNGE4OTAxZWFkOGEwNzEwOGUxMzk5Mzg3Mzg2Yjg2NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pUYb7if2WxxWQ_ySP_wqMt004SwPM-S0kiDJMsLtcMk) 现在问题是，我在节点管理里面能看到这个节点，但是在创建扫描任务时提示没有可用节点： ![image](https://private-user-images.githubusercontent.com/34560797/339195238-ea54d934-0402-4c1c-bd3b-c3e9a68360d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDgxNjYsIm5iZiI6MTcxODI0Nzg2NiwicGF0aCI6Ii8zNDU2MDc5Ny8zMzkxOTUyMzgtZWE1NGQ5MzQtMDQwMi00YzFjLWJkM2ItYzNlOWE2ODM2MGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAzMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZTA4ZWVjMGY3ZjFkOGM0NWQwNzc0NGE1MTgzNDcyZWVkY2Y4YTUxNWFjZmEzOWJmMDY4YmQwNTkwY2IzNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZVdMT7bsCgL8dIBXFfTE7TBXyjgAymZ4u20axSyAtw)
> 
> 看起来是时区出了问题，可以看看系统配置是不是找不到这个时区，节点管理那里的更新时间为空，扫描节点会根据更新时间判断节点是否存活，所以就导致了节点为空的情况

我给它改成直接获取Local再编译，就可以了。
