### ISSUE TITLE
本项目docker启用后，ufw无法实现对相关端口实现限制的解决方案

### ISSUE THREAD

**Issue by xinyuzhang456** [Autumn-27/ScopeSentry#100]
添加docker后，发现ufw无法对docker运行对外提供的端口进行限制
提供下面的解决方案  
查看策略：iptables -nvL       
先默认将指定端口禁止访问：iptables -I DOCKER-USER   -p tcp --dport 端口号 -j DROP
再将指定端口放通至只指定ipiptables -I DOCKER-USER -s 允许访问的ip -p tcp --dport 允许访问的端口 -j ACCEPT

**Comment by Autumn-27** [comment]
已放到常见问题中
