### ISSUE TITLE
无法启动域名扫描

### ISSUE THREAD

**Issue by heyao1996** [Autumn-27/ScopeSentry#102]
![image](https://github.com/user-attachments/assets/e9220d8a-0cc8-41ab-ad81-9fba18aa89c3)
![image](https://github.com/user-attachments/assets/7cc9929a-17a3-467b-9097-8689181c3a05)
就一直卡这了，0%，任务不跑，输入ip可以正常扫描

**Comment by Autumn-27** [comment]
点个暂停 然后再点个开始

**Comment by Autumn-27** [comment]
有可能是前一个任务没执行完毕
