### ISSUE TITLE
扫描任务进度一直卡在0%

### ISSUE THREAD

**Issue by mysterious-sec** [Autumn-27/ScopeSentry#11]
各服务都正常，但扫描任务进度一直卡在0%，辛苦师傅空了看下
服务器：Ubuntu 20.04

**Comment by Autumn-27** [comment]
> 各服务都正常，但扫描任务进度一直卡在0%，辛苦师傅空了看下 服务器：Ubuntu 20.04

好的

**Comment by 7Shad0w** [comment]
> 各服务都正常，但扫描任务进度一直卡在0%，辛苦师傅空了看下 服务器：Ubuntu 20.04

我自己测下来是scan没有启动好，你自己进容器后重新再启动一次即可

**Comment by Autumn-27** [comment]
这里应该有的系统有bug  有的系统docker需要安装个依赖 一个版本修复

**Comment by Autumn-27** [comment]
> 各服务都正常，但扫描任务进度一直卡在0%，辛苦师傅空了看下 服务器：Ubuntu 20.04

师傅试下最新版看看还有没有这个问题

**Comment by khanjanny** [comment]
yes i have tried latest one it seems it just stuck on 0%

**Comment by Autumn-27** [comment]
任务进度一直为0排查:
1.确保启动scan容器设置了network_mode: host
2.进入容器ls 查看ScopeSentry目录是否生成ksubdomain配置文件
3.如果没有配置文件 执行ext/ksubdomain/ksubdomain test 查看是否可以执行成功,如果没有执行成功说明docker容器内获取不到dns流量,排查docker相关的网络设置(避免这个问题可以选择不用docker运行scan,下载可执行文件运行也是一样的)


如果扫描子域名数量为0
看ksubdomain的配置文件,将里边的ip换成公网ip

**Comment by Autumn-27** [comment]
出现这个问题建议不用docker运行扫描节点，直接下载scan的二进制程序运行
https://www.scope-sentry.top/guide/install/#%E7%9B%B4%E6%8E%A5%E8%BF%90%E8%A1%8C
