### ISSUE TITLE
pip安装库问题

### ISSUE THREAD

**Issue by chenchen123423** [Autumn-27/ScopeSentry#12]
pip安装库问题 一直报错每个库版本都找不到，太麻烦了python3.7,
ERROR: Could not find a version that satisfies the requirement pydantic_core==2.14.6 (from versions: none)
ERROR: No matching distribution found for pydantic_core==2.14.6

**Comment by Autumn-27** [comment]
> pip安装库问题 一直报错每个库版本都找不到，太麻烦了python3.7,
> 
> ERROR: Could not find a version that satisfies the requirement pydantic_core==2.14.6 (from versions: none)
> 
> ERROR: No matching distribution found for pydantic_core==2.14.6
> 
> 

把这个库删掉吧 应该也能运行

**Comment by chenchen123423** [comment]
每个库都爆这样的错，我直接把版本号删除然后pip -t再安装吗大佬

**Comment by Autumn-27** [comment]
> 每个库都爆这样的错，我直接把版本号删除然后pip -t再安装吗大佬

看错了 我还以为是第一个库 那可能是你环境问题 换个源看看
