### ISSUE TITLE
单机部署 scope-sentry组件一直waiting

### ISSUE THREAD

**Issue by AnubisSH** [Autumn-27/ScopeSentry#13]
![图片](https://github.com/Autumn-27/ScopeSentry/assets/28776455/a9591047-9ba5-4914-8fd4-5a4a1875cbe7)
查看日志报错如上

**Comment by Autumn-27** [comment]
> ![图片](https://private-user-images.githubusercontent.com/28776455/339966239-a9591047-9ba5-4914-8fd4-5a4a1875cbe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzkwODEsIm5iZiI6MTcxODQzODc4MSwicGF0aCI6Ii8yODc3NjQ1NS8zMzk5NjYyMzktYTk1OTEwNDctOWJhNS00OTE0LThmZDQtNWE0YTE4NzVjYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA4MDYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYTdjMGQ4MmYwMzZkMmM0OTc0MDE0YWFlMmVlMzZlM2RkNGIzYjZkNDc3ZWM1ODlkMTU2NzFkZjYzNzY0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zPophcvmTmi4kHBl6K27XBTwaaDtABYIkbU1ciOnP4E) 查看日志报错如上

重启一下这个容器，是由于mongodb启动慢 server启动的时候mongodb还没启动，修复中。

**Comment by freeAhao** [comment]
```
scope-sentry         | During handling of the above exception, another exception occurred:
scope-sentry         |
scope-sentry         | Traceback (most recent call last):
scope-sentry         |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 677, in lifespan
scope-sentry         |     async with self.lifespan_context(app) as maybe_state:
scope-sentry         |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __aenter__
scope-sentry         |     await self._router.startup()
scope-sentry         |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 654, in startup
scope-sentry         |     await handler()
scope-sentry         |   File "/opt/ScopeSentry/main.py", line 32, in startup_db_client
scope-sentry         |     await db.create_database()
scope-sentry         |   File "/opt/ScopeSentry/core/db.py", line 146, in create_database
scope-sentry         |     exit(0)
scope-sentry         |   File "/usr/local/lib/python3.7/_sitebuiltins.py", line 26, in __call__
scope-sentry         |     raise SystemExit(code)
scope-sentry         | SystemExit: 0
scope-sentry         |
scope-sentry         | ERROR:    Application startup failed. Exiting.
scopesentry-mongodb  |
scopesentry-mongodb  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
scopesentry-mongodb  |   see https://jira.mongodb.org/browse/SERVER-54407
scopesentry-mongodb  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
scopesentry-mongodb  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
scopesentry-mongodb  |
scopesentry-mongodb  | /usr/local/bin/docker-entrypoint.sh: line 416:    26 Illegal instruction     "${mongodHackedArgs[@]}" --fork
scopesentry-mongodb exited with code 132
scopesentry-mongodb  |
scopesentry-mongodb  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
scopesentry-mongodb  |   see https://jira.mongodb.org/browse/SERVER-54407
scopesentry-mongodb  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
scopesentry-mongodb  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
scopesentry-mongodb  |
scopesentry-mongodb  | /usr/local/bin/docker-entrypoint.sh: line 416:    26 Illegal instruction     "${mongodHackedArgs[@]}" --fork
scopesentry-mongodb exited with code 132
scopesentry-mongodb  |
scopesentry-mongodb  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
scopesentry-mongodb  |   see https://jira.mongodb.org/browse/SERVER-54407
scopesentry-mongodb  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
scopesentry-mongodb  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
scopesentry-mongodb  |
scopesentry-mongodb  | /usr/local/bin/docker-entrypoint.sh: line 416:    27 Illegal instruction     "${mongodHackedArgs[@]}" --fork
scopesentry-mongodb exited with code 132
scopesentry-mongodb  |
scopesentry-mongodb  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
scopesentry-mongodb  |   see https://jira.mongodb.org/browse/SERVER-54407
scopesentry-mongodb  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
scopesentry-mongodb  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
scopesentry-mongodb  |
scopesentry-mongodb  | /usr/local/bin/docker-entrypoint.sh: line 416:    26 Illegal instruction     "${mongodHackedArgs[@]}" --fork
scopesentry-mongodb exited with code 132
```

**Comment by Autumn-27** [comment]
> ```
> scope-sentry         | During handling of the above exception, another exception occurred:
> scope-sentry         |
> scope-sentry         | Traceback (most recent call last):
> scope-sentry         |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 677, in lifespan
> scope-sentry         |     async with self.lifespan_context(app) as maybe_state:
> scope-sentry         |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __aenter__
> scope-sentry         |     await self._router.startup()
> scope-sentry         |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 654, in startup
> scope-sentry         |     await handler()
> scope-sentry         |   File "/opt/ScopeSentry/main.py", line 32, in startup_db_client
> scope-sentry         |     await db.create_database()
> scope-sentry         |   File "/opt/ScopeSentry/core/db.py", line 146, in create_database
> scope-sentry         |     exit(0)
> scope-sentry         |   File "/usr/local/lib/python3.7/_sitebuiltins.py", line 26, in __call__
> scope-sentry         |     raise SystemExit(code)
> scope-sentry         | SystemExit: 0
> scope-sentry         |
> scope-sentry         | ERROR:    Application startup failed. Exiting.
> scopesentry-mongodb  |
> scopesentry-mongodb  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
> scopesentry-mongodb  |   see https://jira.mongodb.org/browse/SERVER-54407
> scopesentry-mongodb  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
> scopesentry-mongodb  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
> scopesentry-mongodb  |
> scopesentry-mongodb  | /usr/local/bin/docker-entrypoint.sh: line 416:    26 Illegal instruction     "${mongodHackedArgs[@]}" --fork
> scopesentry-mongodb exited with code 132
> scopesentry-mongodb  |
> scopesentry-mongodb  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
> scopesentry-mongodb  |   see https://jira.mongodb.org/browse/SERVER-54407
> scopesentry-mongodb  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
> scopesentry-mongodb  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
> scopesentry-mongodb  |
> scopesentry-mongodb  | /usr/local/bin/docker-entrypoint.sh: line 416:    26 Illegal instruction     "${mongodHackedArgs[@]}" --fork
> scopesentry-mongodb exited with code 132
> scopesentry-mongodb  |
> scopesentry-mongodb  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
> scopesentry-mongodb  |   see https://jira.mongodb.org/browse/SERVER-54407
> scopesentry-mongodb  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
> scopesentry-mongodb  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
> scopesentry-mongodb  |
> scopesentry-mongodb  | /usr/local/bin/docker-entrypoint.sh: line 416:    27 Illegal instruction     "${mongodHackedArgs[@]}" --fork
> scopesentry-mongodb exited with code 132
> scopesentry-mongodb  |
> scopesentry-mongodb  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
> scopesentry-mongodb  |   see https://jira.mongodb.org/browse/SERVER-54407
> scopesentry-mongodb  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
> scopesentry-mongodb  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
> scopesentry-mongodb  |
> scopesentry-mongodb  | /usr/local/bin/docker-entrypoint.sh: line 416:    26 Illegal instruction     "${mongodHackedArgs[@]}" --fork
> scopesentry-mongodb exited with code 132
> ```

mongodb版本问题
