### ISSUE TITLE
socker 版本不兼容问题

### ISSUE THREAD

**Issue by AMJIYU** [Autumn-27/ScopeSentry#15]
当在mac 上上python main.py  源码方式运行，会报错如下：

bute 'TCP_KEEPIDLE'. Reconnecting...
2024-06-16 20:00:03.720 | ERROR    | core.redis_handler:subscribe_log_channel:79 - An error occurred: module 'socket' has no attribute 'TCP_KEEPIDLE'. Reconnecting...
<img width="1433" alt="image" src="https://github.com/Autumn-27/ScopeSentry/assets/21239564/6072dade-e89e-4abf-90b8-4313ccd3533d">

core.redis_handler.py  函数get_redis_pool需要修改：
            # mac 平台应该是
            socket.TCP_KEEPALIVE: 60,
            #socket.TCP_KEEPIDLE: 60, 只针对与linux平台
<img width="687" alt="image" src="https://github.com/Autumn-27/ScopeSentry/assets/21239564/da8e41a9-e514-4c8a-86d2-ca6638b79835">

**Comment by Autumn-27** [comment]
好的
