### ISSUE TITLE
Container  unhealthy 报错 请问如何解决

### ISSUE THREAD

**Issue by Solan999** [Autumn-27/ScopeSentry#17]
ERROR: for scopesentry-scan  Container "4cde735a96fa" is unhealthy.

Container  unhealthy 报错 请问如何解决

![图片](https://github.com/Autumn-27/ScopeSentry/assets/103107845/5ecd0fa4-6c73-4ccd-963d-de77d53c716b)

**Comment by Autumn-27** [comment]
> ERROR: for scopesentry-scan Container "4cde735a96fa" is unhealthy.
> 
> Container unhealthy 报错 请问如何解决
> 
> ![图片](https://private-user-images.githubusercontent.com/103107845/340599974-5ecd0fa4-6c73-4ccd-963d-de77d53c716b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTk0ODEsIm5iZiI6MTcxODY5OTE4MSwicGF0aCI6Ii8xMDMxMDc4NDUvMzQwNTk5OTc0LTVlY2QwZmE0LTZjNzMtNGNjZC05NjNkLWRlNzdkNTNjNzE2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwODI2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWE5MmVjMTA1YzUyMjVjYjNlYTQxZWRjM2MyNWVkNjVjNTQxYjc1ZjJjMmI3YjY1Njg2YTFiMGI1N2I0NzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-5FKUNhdqOeuBVXKd6kcfrMTSucVOK_Bb0bPeCQVOCE)

给个日志

**Comment by Solan999** [comment]
![图片](https://github.com/Autumn-27/ScopeSentry/assets/103107845/2be67be1-6aba-491e-9940-c9ac419a6441)
如上，感谢！

**Comment by Autumn-27** [comment]
> ![图片](https://private-user-images.githubusercontent.com/103107845/340601610-2be67be1-6aba-491e-9940-c9ac419a6441.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTk3NTUsIm5iZiI6MTcxODY5OTQ1NSwicGF0aCI6Ii8xMDMxMDc4NDUvMzQwNjAxNjEwLTJiZTY3YmUxLTZhYmEtNDkxZS05OTQwLWM5YWM0MTlhNjQ0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwODMwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmE4YmFkOTYyZDc4Zjc1MmExODA1N2I3NmU5M2RjYzQ0Y2YxYTgyMzUyMmIwODQ0Njk3MjgzZWY1YTEyMzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.11PmaK1NKlX3PuWIyvuz2bJvrPB9opWbRtj8nWY4dz4) 如上，感谢！

报错不是有说明解决方案嘛

**Comment by Solan999** [comment]
看到了看到了，感谢

**Comment by Autumn-27** [comment]
> 看到了看到了，感谢

好的，这个可能是系统的问题
