### ISSUE TITLE
502错误

### ISSUE THREAD

**Issue by BroderickER** [Autumn-27/ScopeSentry#18]
INFO:     Started server process [37]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/opt/ScopeSentry/main.py", line 66, in startup_db_client
    pat = await get_page_monitoring_time()
  File "/opt/ScopeSentry/api/scheduled_tasks.py", line 147, in get_page_monitoring_time
    async for db in get_mongo_db():
  File "/opt/ScopeSentry/core/db.py", line 17, in get_mongo_db
    serverSelectionTimeoutMS=10000, unicode_decode_error_handler='ignore')
  File "/usr/local/lib/python3.7/site-packages/motor/core.py", line 163, in __init__
    delegate = self.__delegate_class__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 779, in __init__
    srv_max_hosts=srv_max_hosts,
  File "/usr/local/lib/python3.7/site-packages/pymongo/uri_parser.py", line 534, in parse_uri
    user, passwd = parse_userinfo(userinfo)
  File "/usr/local/lib/python3.7/site-packages/pymongo/uri_parser.py", line 86, in parse_userinfo
    "Username and password must be escaped according to "
pymongo.errors.InvalidURI: Username and password must be escaped according to RFC 3986, use urllib.parse.quote_plus

ERROR:    Application startup failed. Exiting.

**Comment by Autumn-27** [comment]
> INFO:     Started server process [37]
> 
> INFO:     Waiting for application startup.
> 
> ERROR:    Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 677, in lifespan
> 
>     async with self.lifespan_context(app) as maybe_state:
> 
>   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __aenter__
> 
>     await self._router.startup()
> 
>   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 654, in startup
> 
>     await handler()
> 
>   File "/opt/ScopeSentry/main.py", line 66, in startup_db_client
> 
>     pat = await get_page_monitoring_time()
> 
>   File "/opt/ScopeSentry/api/scheduled_tasks.py", line 147, in get_page_monitoring_time
> 
>     async for db in get_mongo_db():
> 
>   File "/opt/ScopeSentry/core/db.py", line 17, in get_mongo_db
> 
>     serverSelectionTimeoutMS=10000, unicode_decode_error_handler='ignore')
> 
>   File "/usr/local/lib/python3.7/site-packages/motor/core.py", line 163, in __init__
> 
>     delegate = self.__delegate_class__(*args, **kwargs)
> 
>   File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 779, in __init__
> 
>     srv_max_hosts=srv_max_hosts,
> 
>   File "/usr/local/lib/python3.7/site-packages/pymongo/uri_parser.py", line 534, in parse_uri
> 
>     user, passwd = parse_userinfo(userinfo)
> 
>   File "/usr/local/lib/python3.7/site-packages/pymongo/uri_parser.py", line 86, in parse_userinfo
> 
>     "Username and password must be escaped according to "
> 
> pymongo.errors.InvalidURI: Username and password must be escaped according to RFC 3986, use urllib.parse.quote_plus
> 
> 
> 
> ERROR:    Application startup failed. Exiting.
> 
> 

账号密码别用特殊字符
