### ISSUE TITLE
资产希望支持导出，并添加资产备注/自定义字段功能

### ISSUE THREAD

**Issue by JoJenH** [Autumn-27/ScopeSentry#2]
希望讲该工具用于甲方资产梳理，可以自行标注所属部门/负责人等

**Comment by Autumn-27** [comment]
> 希望讲该工具用于甲方资产梳理，可以自行标注所属部门/负责人等

![image](https://github.com/Autumn-27/ScopeSentry/assets/53844290/0ef9fc28-dee0-40d2-90fb-20282336758e)


师傅 可以加下好友详细说一下

**Comment by tgbhj** [comment]
希望资产测绘、子域名、URL可以支持导出成excel或csv格式
