### ISSUE TITLE
Windows运行1.3版本ScopeSentry-scan报错Error loading time zone

### ISSUE THREAD

**Issue by myname365** [Autumn-27/ScopeSentry#20]
![图片](https://github.com/Autumn-27/ScopeSentry/assets/133751744/a5873bff-0c4f-4beb-bdec-670a59466770)
Error loading time zone:%!(EXTRA *errors.errorString=unknown time zone Asia/Shanghai)

**Comment by Autumn-27** [comment]
> ![图片](https://github.com/Autumn-27/ScopeSentry/assets/133751744/a5873bff-0c4f-4beb-bdec-670a59466770)
> 
> Error loading time zone:%!(EXTRA *errors.errorString=unknown time zone Asia/Shanghai)

好像windows没找到时区 换个时区或者看看能不能加个时区

**Comment by myname365** [comment]
改完会被服务端同步回去，又改回来了。
