### ISSUE TITLE
docker-compose up -d 报错

### ISSUE THREAD

**Issue by wcxxxxx** [Autumn-27/ScopeSentry#23]
ERROR: The Compose file './single-host-deployment.yml' is invalid because:
services.scopesentry-scan.depends_on contains an invalid type, it should be an array

问了GPT，更改为：
  scopesentry-scan:
    depends_on:
      - redis
      - scope-sentry
可以运行，但是一直502，不知道有没有影响

docker logs日志为
2024-06-20 09:25:43.448 | ERROR    | core.db:create_database:155 - Error creating database: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}

**Comment by Autumn-27** [comment]
> ERROR: The Compose file './single-host-deployment.yml' is invalid because:
> 
> services.scopesentry-scan.depends_on contains an invalid type, it should be an array
> 
> 
> 
> 问了GPT，更改为：
> 
>   scopesentry-scan:
> 
>     depends_on:
> 
>       - redis
> 
>       - scope-sentry
> 
> 可以运行，但是一直502，不知道有没有影响
> 
> 
> 
> docker logs日志为
> 
> 2024-06-20 09:25:43.448 | ERROR    | core.db:create_database:155 - Error creating database: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}
> 
> 

server里边的配置文件 数据库账号密码不对

**Comment by xiaojumaoaihuaban** [comment]
可以尝试一下：
docker compose -f single-host-deployment.yml up -d
我就成功了，compose版本有的要加-
希望对你有帮助
