### ISSUE TITLE
查询信息卡

### ISSUE THREAD

**Issue by alchu4n** [Autumn-27/ScopeSentry#24]
![image](https://github.com/Autumn-27/ScopeSentry/assets/97670155/55fec71e-9226-4577-a679-8ab63b672a73)

**Comment by Autumn-27** [comment]
> ![image](https://github.com/Autumn-27/ScopeSentry/assets/97670155/55fec71e-9226-4577-a679-8ab63b672a73)
> 
> 

数据量有多少呀？

**Comment by alchu4n** [comment]
> > ![image](https://private-user-images.githubusercontent.com/97670155/341602374-55fec71e-9226-4577-a679-8ab63b672a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MzQ3MjMsIm5iZiI6MTcxODkzNDQyMywicGF0aCI6Ii85NzY3MDE1NS8zNDE2MDIzNzQtNTVmZWM3MWUtOTIyNi00NTc3LWE2NzktOGFiNjNiNjcyYTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDAxNDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MWJjZTkzYjI4OTIxMWI3Yjg1YWJmMGY2MWE3ZjI1YzBiNGIxODQzNTE5NGQ4NGM2M2ZkOTUxMTFmMGI4ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xGrl1lSQtXBODoR2fhJB7WqYU3QgSaponp4OKte_reI)
> 
> 数据量有多少呀？

![image](https://github.com/Autumn-27/ScopeSentry/assets/97670155/a736106f-4496-4683-aa2e-83fc3480b1ed)


![image](https://github.com/Autumn-27/ScopeSentry/assets/97670155/185ad577-a2bb-4b4b-9f0b-d51097ec0472)


![image](https://github.com/Autumn-27/ScopeSentry/assets/97670155/f7fd62b1-cf56-4e24-a3c4-f18c685a15e6)

**Comment by alchu4n** [comment]
数据量不大，但是再查询时明显感觉系统卡

**Comment by Autumn-27** [comment]
单机部署的吗？ 可以看下f12 看下各个接口请求时间

**Comment by alchu4n** [comment]
> 单机部署的吗？ 可以看下f12 看下各个接口请求时间

是的 单机docker部署 请求的速度时好时慢。

**Comment by Autumn-27** [comment]
系统配置嘞？ 看下接口请求哪个耗时最多吧 我看看能不能优化一下

**Comment by alchu4n** [comment]
资产信息查询页面的接口
