### ISSUE TITLE
docker拉不起来

### ISSUE THREAD

**Issue by xing-t** [Autumn-27/ScopeSentry#3]
网络应该没有问题拉灯塔没有问题，师傅能看下是不是远程仓库的问题呢
![image](https://github.com/Autumn-27/ScopeSentry/assets/56910350/14d60d78-b37a-46a0-b70d-a40e3a2ad68f)

**Comment by Autumn-27** [comment]
> 网络应该没有问题拉灯塔没有问题，师傅能看下是不是远程仓库的问题呢
> 
> ![image](https://github.com/Autumn-27/ScopeSentry/assets/56910350/14d60d78-b37a-46a0-b70d-a40e3a2ad68f)
> 
> 

应该是dockerhub被墙的原因 阿里云的可以用吗？现在手边没电脑过两天我找个备选方案

**Comment by xing-t** [comment]
华为云拉的不行

**Comment by muYoz** [comment]
阿里源不行，目前可行的方案：
vi /etc/docker/daemon.json

{
  "registry-mirrors": ["https://do.nark.eu.org"]
}

sudo systemctl daemon-reload
sudo systemctl restart docker

**Comment by Lamber-maybe** [comment]
# Linux系统，让Docker直接走梯子翻墙

> 省得找镜像了

1. 为 docker 服务创建一个 systemd drop-in 目录
```bash
sudo mkdir -p /etc/systemd/system/docker.service.d
```
3. 创建名为 `/etc/systemd/system/docker.service.d/http-proxy.conf` 的文件，添加 `HTTP_PROXY` 和 `HTTPS_PROXY` 环境变量：
```bash
[Service]
Environment="HTTP_PROXY=http://192.168.17.1:7890"
Environment="HTTPS_PROXY=http://192.168.17.1:7890"
```
4. 添加白名单，不使用代理(可选)
```bash
Environment="NO_PROXY=localhost,127.0.0.1,docker-registry.example.com,.corp"
```
5. 更新配置文件并重启 Docker
```bash
sudo systemctl daemon-reload
sudo systemctl restart docker
```
6. 验证配置文件是否正确
```bash
sudo systemctl show --property=Environment docker
```

**Comment by Autumn-27** [comment]
镜像可通过https://mirror.adysec.com/container/docker-hub/ 拉取
