### ISSUE TITLE
架构选型请教

### ISSUE THREAD

**Issue by V3teran** [Autumn-27/ScopeSentry#34]
请问师傅，在数据库选型的时候，为何选用非关系型数据库mongodb而不是关系型数据库如mysql呢，思考的点有哪些呢，有什么坑吗？

**Comment by Autumn-27** [comment]
> 请问师傅，在数据库选型的时候，为何选用非关系型数据库mongodb而不是关系型数据库如mysql呢，思考的点有哪些呢，有什么坑吗？

主要是考虑资产数据类型不一样，mongodb拓展存储字段比较方便修改。
