### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by obelia01** [Autumn-27/ScopeSentry#35]
我现在重启web端后，产生Request failed with status code 500报错信息，数据库我看了没问题

**Comment by Autumn-27** [comment]
看看日志..

**Comment by obelia01** [comment]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
  
<img width="1010" alt="image" src="https://github.com/Autumn-27/ScopeSentry/assets/82713832/8d861c77-8ef5-4eaa-bf96-8ce69722e82e">

redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

**Comment by obelia01** [comment]
可能是redis 有问题了

**Comment by Autumn-27** [comment]
嗯嗯 docker搭建的吗？ 看看redis的日志

**Comment by obelia01** [comment]
<img width="1225" alt="image" src="https://github.com/Autumn-27/ScopeSentry/assets/82713832/5006f6fd-bab0-4c9e-a9de-64d1b52398aa">
10069:C 04 Jul 2024 05:05:16.083 # Failed opening the temp RDB file temp-10069.rdb (in server root dir unknown) for saving: No such file or directory
1:M 04 Jul 2024 05:05:16.183 # Background saving error
1:M 04 Jul 2024 05:05:22.099 * 1 changes in 3600 seconds. Saving...
1:M 04 Jul 2024 05:05:22.099 * Background saving started by pid 10070
10070:C 04 Jul 2024 05:05:22.099 # Failed opening the temp RDB file temp-10070.rdb (in server root dir unknown) for saving: No such file or directory
1:M 04 Jul 2024 05:05:22.199 # Background saving error
基本上都是这个报错信息。。。。是不是得重新搭redis ，数据应该都在mongdb上吧

**Comment by Autumn-27** [comment]
你查一下 应该可以解决 数据都在mongodb上

**Comment by obelia01** [comment]
emmmm，redis 重启以后，timeout了 
<img width="437" alt="image" src="https://github.com/Autumn-27/ScopeSentry/assets/82713832/28768e4b-6089-4599-8db8-b7f46e275121">

<img width="1007" alt="image" src="https://github.com/Autumn-27/ScopeSentry/assets/82713832/0df892a4-c29e-4f18-bfd7-59b71fedb00e">


可能在数据同步，我明天看看

**Comment by Autumn-27** [comment]
服务端也重启一下吧

**Comment by obelia01** [comment]
服务端重启报错
<img width="320" alt="image" src="https://github.com/Autumn-27/ScopeSentry/assets/82713832/2b07f35a-0fbb-4ee3-8f2e-ce368d87d0dd">
好像数据丢了。。。。

**Comment by Autumn-27** [comment]
看日志 重启和数据应该没有关系

**Comment by obelia01** [comment]
<img width="1010" alt="image" src="https://github.com/Autumn-27/ScopeSentry/assets/82713832/576d6aec-70d7-46ad-b735-94f3c7ab562e">
还是有报错 。。

**Comment by obelia01** [comment]
<img width="1306" alt="image" src="https://github.com/Autumn-27/ScopeSentry/assets/82713832/c495c0b1-47d4-4e9e-bf91-51cf21d4e6b7">

redis 有报错，我铲掉redis 重新部署一下吧

**Comment by obelia01** [comment]
<img width="1010" alt="image" src="https://github.com/Autumn-27/ScopeSentry/assets/82713832/2d26a9a8-3850-4713-b106-522eac29d5a4">

<img width="1010" alt="image" src="https://github.com/Autumn-27/ScopeSentry/assets/82713832/04564ac7-b85a-458d-be2c-09cd40fd4cba">



还是有问题。。。。。。。
