### ISSUE TITLE
可以弄一个arm架构的docker版的嘛

### ISSUE THREAD

**Issue by FeiNiao** [Autumn-27/ScopeSentry#4]
![image](https://github.com/Autumn-27/ScopeSentry/assets/66779835/4decc8b0-291d-44fd-bc4c-60c723d42860)

arm运行不起来

**Comment by Autumn-27** [comment]
> ![image](https://github.com/Autumn-27/ScopeSentry/assets/66779835/4decc8b0-291d-44fd-bc4c-60c723d42860)
> 
> 
> 
> arm运行不起来

好 可能得过段时间

**Comment by Sa11Sec** [comment]
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/8bacac55-e2d9-4c94-9a25-55f830a2ea99">
同求 ARM 架构

**Comment by Autumn-27** [comment]
可以源码编译运行 主要是有一些依赖工具没有arm版本的 没有环境不知道是否能用
