### ISSUE TITLE
发现了一个BUG

### ISSUE THREAD

**Issue by AvaterXXX** [Autumn-27/ScopeSentry#40]
先用docker运行，字典管理都是可以查看的，之后关闭autumn27/scopesentry，保留mongodb和redis，改用源码启动，此时字典管理的目录子域名会报错，无法查看。再次打开autumn27/scopesentry容器后，依旧报错
![image](https://github.com/user-attachments/assets/d87f1ea8-0ac7-400b-97b2-e85f4fc73916)
看了源码也没发现什么问题，不知道是怎么产生的这个bug

**Comment by Autumn-27** [comment]
我的锅 源码有些修改我直接在主分支上改了 这里新版有改动 所以才不显示
