### ISSUE TITLE
怎么创建节点？

### ISSUE THREAD

**Issue by Hangoverst** [Autumn-27/ScopeSentry#41]
节点管理里面是空的，怎么新建节点呢？
![image](https://github.com/user-attachments/assets/39de2760-d19c-4491-994f-4557301f4c92)

**Comment by Autumn-27** [comment]
运行节点了吗

**Comment by Hangoverst** [comment]
> 运行节点了吗

我是通过源码安装的，运行了main.py，节点应该运行哪个文件？

**Comment by Autumn-27** [comment]
你看下文档 一共四个服务
