### ISSUE TITLE
Subdomain not showing or not able to scan subdomain

### ISSUE THREAD

**Issue by khanjanny** [Autumn-27/ScopeSentry#48]
Log showing number of subdomain found but on Asset Information page if i navigate to subdomain there was not subdomain on that page. 

Also in new version 1.4 on project-management page any of the project is not clickable anymore.

**Comment by Autumn-27** [comment]
The subdomain found by subfinder in the log will determine whether the subdomain is still alive, and you can manually determine whether the domain name still exists. The project click becomes right-clicked.
