### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by mortal-sec** [Autumn-27/ScopeSentry#49]
目前我看到在指纹信息和目录扫描里面没有nacos的指纹，建议优化一下指纹以及字典比如添加一些api spring nacos env常见路径，扫描的时候由于nuclei的低危无用信息很多，建议扫描的时候可以选择分组，比如只选择高危或者严重类别的扫描

**Comment by Autumn-27** [comment]
字典这个看自己收集的自己添加吧 漏扫在计划中了

**Comment by Autumn-27** [comment]
或者可以分享一下字典
