### ISSUE TITLE
单节点部署拉取docker镜像错误

### ISSUE THREAD

**Issue by michaoxj** [Autumn-27/ScopeSentry#50]
错误提示：
ERROR: The Compose file './single-host-deployment.yml' is invalid because:
services.scope-sentry.depends_on contains an invalid type, it should be an array
services.scopesentry-scan.depends_on contains an invalid type, it should be an array

git下来的源码。

**Comment by Autumn-27** [comment]
#45

**Comment by Lufei101** [comment]
git的源码，单点部署，在拉取镜像是报错：
/usr/local/lib/python3.6/site-packages/OpenSSL/_util.py:6: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.bindings.openssl.binding import Binding
Pulling mongodb (mongo:7.0.4)...
ERROR: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

该怎么解决

**Comment by Autumn-27** [comment]
> git的源码，单点部署，在拉取镜像是报错：
> 
> /usr/local/lib/python3.6/site-packages/OpenSSL/_util.py:6: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
> 
>   from cryptography.hazmat.bindings.openssl.binding import Binding
> 
> Pulling mongodb (mongo:7.0.4)...
> 
> ERROR: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> 
> 
> 
> 该怎么解决

https://mirror.adysec.com/container/docker-hub/
