### ISSUE TITLE
资产导出失败

### ISSUE THREAD

**Issue by shen771** [Autumn-27/ScopeSentry#51]
扫描完成后，资产信息里导出提示报错get index, quantity, export_type null，导出所有/当前搜索条件均报错
![23](https://github.com/user-attachments/assets/53b860d9-9eb0-4a97-9c5c-81c3f0371218)

**Comment by Autumn-27** [comment]
你到处数据写的是0

**Comment by shen771** [comment]
我写20000或者不些，也一样的报错

**Comment by Autumn-27** [comment]
看下server的日志报错信息

**Comment by shen771** [comment]
不好意思师傅，我今天重新启动了下，再测试未能复现此现象，填非0数字是可以导出的，后续我再观察观察，有问题取log，打扰了

**Comment by Autumn-27** [comment]
好的

**Comment by forktopot** [comment]
> 好的

数据量稍大导出就会报错，我只填到两百就报错了
![image](https://github.com/user-attachments/assets/1beb208a-41d3-47cf-afb5-52929d8595c5)
![image](https://github.com/user-attachments/assets/55582e1d-9df6-461e-ba7f-d27ca45ea936)
这个错误表示在向 Excel 工作表中写入数据时遇到非法字符。字符 R 后面可能有一个不可见的非法字符，导致 openpyxl 无法处理该值

**Comment by forktopot** [comment]
> 好的

进入docker 中查看，确实也没有生成文件，只有几个小的生成成功了 
![image](https://github.com/user-attachments/assets/109afb42-19a0-44d4-9102-a3ba13d249b2)

**Comment by Autumn-27** [comment]
我记得我处理非法字符了 奇怪 之后我再修复一下

**Comment by forktopot** [comment]
> 我记得我处理非法字符了 奇怪 之后我再修复一下

![image](https://github.com/user-attachments/assets/f52ad1ed-41c0-45a2-885a-33e891ce79d3)
这边接口显示任务成功，但是实际上没有

**Comment by Autumn-27** [comment]
> > 我记得我处理非法字符了 奇怪 之后我再修复一下
> 
> ![image](https://private-user-images.githubusercontent.com/24220639/355289101-f52ad1ed-41c0-45a2-885a-33e891ce79d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTA5MzYsIm5iZiI6MTcyMjkxMDYzNiwicGF0aCI6Ii8yNDIyMDYzOS8zNTUyODkxMDEtZjUyYWQxZWQtNDFjMC00NWEyLTg4NWEtMzNlODkxY2U3OWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAyMTcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkM2FiMGFjZDNiNWY5ODE3ZWYyMDY1YjdlNWMzZWYzOTE3Y2ZmZjk5ZDkyMDY1YmQ1MDhiMWFiMjc3YTQxZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QXy2Xc-stfaIs5boldnmhI6tfBxZSPtg9CCgYH700aE) 这边接口显示任务成功，但是实际上没有

这个只是创建了导出任务成功，具体是否成功要看导出记录那里
