### ISSUE TITLE
希望资产信息中可以增加IP端口资产

### ISSUE THREAD

**Issue by niannianyo** [Autumn-27/ScopeSentry#54]
即端口扫描结果，目前资产中是无法直接搜索到ip端口结果，读取ip是有很多域名解析ip，是cdnip

**Comment by Autumn-27** [comment]
是想根据ip聚合开放端口吗？

**Comment by forktopot** [comment]
> 是想根据ip聚合开放端口吗？

最好是在资产信息哪里有一个选项是 ip 和端口 加服务这种，因为其他服务端口也是需要重点关注的，不仅仅只是http

**Comment by niannianyo** [comment]
> > 是想根据ip聚合开放端口吗？
> 
> 最好是在资产信息哪里有一个选项是 ip 和端口 加服务这种，因为其他服务端口也是需要重点关注的，不仅仅只是http

对，我也是这个意思，我想知道我扫描的ip的端口结果，服务、指纹，目前资产无法展示ip资产

**Comment by niannianyo** [comment]
> 是想根据ip聚合开放端口吗？

这样也可以，根据扫描结果，独立ip 端口 服务 一行也可以

**Comment by Autumn-27** [comment]
明白 需求+1 后边做
