### ISSUE TITLE
新建任务的时候可以直接选择已有项目吗

### ISSUE THREAD

**Issue by handbye** [Autumn-27/ScopeSentry#59]
这样就可以直接扫描已有项目中添加的资产

**Comment by Autumn-27** [comment]
项目那里也可以运行任务 但是目前从项目运行的任务不方便查看任务进度，目前是建议新建任务，之后这里逻辑会进行优化

**Comment by handbye** [comment]
> 项目那里也可以运行任务 但是目前从项目运行的任务不方便查看任务进度，目前是建议新建任务，之后这里逻辑会进行优化

谢谢
