### ISSUE TITLE
mongodb数据库连接错误

### ISSUE THREAD

**Issue by FP1uto** [Autumn-27/ScopeSentry#6]
用docker部署mongodb，然后用docker 启动web服务后，会出现mongodb无法连接的情况。pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

**Comment by Autumn-27** [comment]
> 用docker部署mongodb，然后用docker 启动web服务后，会出现mongodb无法连接的情况。pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

单机部署，docker内ip为127是无法连接的，需要构建docker网络。之后我写个单机部署文档。

**Comment by zzgxpyy** [comment]
我是配置了静态IP

**Comment by Autumn-27** [comment]
> 我是配置了静态IP，但是出现了新的错误：[2024-06-12 17:51:48] ERROR Error: Get "https://update.scope-sentry.top/get/rad?system=linux&arch=amd64": dial tcp: lookup update.scope-sentry.top on 127.0.0.11:53: read udp 127.0.0.1:34150->127.0.0.11:53: i/o timeout 2024-06-12 17:51:48 - [Error] SetUp Config Error 并且 scopesentry-scan 一直在自动重启，间隔时间为23s

这个问题可以手动https://update.scope-sentry.top/get/rad?system=linux&arch=amd64访问 下载可执行文件rad，将文件放入容器的/apps/ext/rad 目录 可执行文件名为rad最终可执行文件的路径为/apps/ext/rad/rad

**Comment by a1most** [comment]
> 我是配置了静态IP，但是出现了新的错误：[2024-06-12 17:51:48] ERROR Error: Get "https://update.scope-sentry.top/get/rad?system=linux&arch=amd64": dial tcp: lookup update.scope-sentry.top on 127.0.0.11:53: read udp 127.0.0.1:34150->127.0.0.11:53: i/o timeout 2024-06-12 17:51:48 - [Error] SetUp Config Error 并且 scopesentry-scan 一直在自动重启，间隔时间为23s

你访问https://update.scope-sentry.top/get/rad?system=linux&arch=amd64这个链接，会下载一个rad，windows下面需要给这个文件增加一个exe的后缀，然后放到scopesentry-scan.exe根目录下面的ext/rad目录下面就行。

**Comment by zzgxpyy** [comment]
> /apps/ext/rad/rad

已经放置了，并且chmod +x了，但是还是会23s自动重启

**Comment by Autumn-27** [comment]
> > /apps/ext/rad/rad
> 
> 已经放置了，并且chmod +x了，但是还是会23s自动重启

看看日志报错

**Comment by zzgxpyy** [comment]
> > > /apps/ext/rad/rad
> > 
> > 
> > 已经放置了，并且chmod +x了，但是还是会23s自动重启
> 
> 看看日志报错

还是这个错误，[2024-06-13 14:49:16]	ERROR	Error: Get "https://update.scope-sentry.top/get/ksubdomain?system=linux&arch=amd64": dial tcp: lookup update.scope-sentry.top on 127.0.0.11:53: read udp 127.0.0.1:46964->127.0.0.11:53: i/o timeout
2024-06-13 14:49:16 - [Error] SetUp Config Error

**Comment by Autumn-27** [comment]
> > > > /apps/ext/rad/rad
> > > 
> > > 
> > > 已经放置了，并且chmod +x了，但是还是会23s自动重启
> > 
> > 
> > 看看日志报错
> 
> 还是这个错误，[2024-06-13 14:49:16] ERROR Error: Get "https://update.scope-sentry.top/get/ksubdomain?system=linux&arch=amd64": dial tcp: lookup update.scope-sentry.top on 127.0.0.11:53: read udp 127.0.0.1:46964->127.0.0.11:53: i/o timeout 2024-06-13 14:49:16 - [Error] SetUp Config Error

这个要放到docker内  ，域名解析有点问题国内可能有时候访问不到，可以暂时不用docker运行，直接运行可执行文件，然后将rad放到ext目录里边。等周末我换一下拉取工具的地址。

**Comment by zzgxpyy** [comment]
> > > > > /apps/ext/rad/rad
> > > > 
> > > > 
> > > > 已经放置了，并且chmod +x了，但是还是会23s自动重启
> > > 
> > > 
> > > 看看日志报错
> > 
> > 
> > 还是这个错误，[2024-06-13 14:49:16] ERROR Error: Get "https://update.scope-sentry.top/get/ksubdomain?system=linux&arch=amd64": dial tcp: lookup update.scope-sentry.top on 127.0.0.11:53: read udp 127.0.0.1:46964->127.0.0.11:53: i/o timeout 2024-06-13 14:49:16 - [Error] SetUp Config Error
> 
> 这个要放到docker内 ，域名解析有点问题国内可能有时候访问不到，可以暂时不用docker运行，直接运行可执行文件，然后将rad放到ext目录里边。等周末我换一下拉取工具的地址。

嗯，是docker cp进去的。你看第一次的错误是 https://update.scope-sentry.top/get/rad?system=linux&arch=amd64，这次的错误是https://update.scope-sentry.top/get/ksubdomain?system=linux&arch=amd64"   ksubdomain的，我的环境可以直接爬tiz。那我再等等吧，昨天的微信群满200了，还有没有其他的二维码，求一个。

**Comment by Autumn-27** [comment]
> > > > > > /apps/ext/rad/rad
> > > > > 
> > > > > 
> > > > > 已经放置了，并且chmod +x了，但是还是会23s自动重启
> > > > 
> > > > 
> > > > 看看日志报错
> > > 
> > > 
> > > 还是这个错误，[2024-06-13 14:49:16] ERROR Error: Get "https://update.scope-sentry.top/get/ksubdomain?system=linux&arch=amd64": dial tcp: lookup update.scope-sentry.top on 127.0.0.11:53: read udp 127.0.0.1:46964->127.0.0.11:53: i/o timeout 2024-06-13 14:49:16 - [Error] SetUp Config Error
> > 
> > 
> > 这个要放到docker内 ，域名解析有点问题国内可能有时候访问不到，可以暂时不用docker运行，直接运行可执行文件，然后将rad放到ext目录里边。等周末我换一下拉取工具的地址。
> 
> 嗯，是docker cp进去的。你看第一次的错误是 [https://update.scope-sentry.top/get/rad?system=linux&arch=amd64，这次的错误是https://update.scope-sentry.top/get/ksubdomain?system=linux&arch=amd64](https://update.scope-sentry.top/get/rad?system=linux&arch=amd64%EF%BC%8C%E8%BF%99%E6%AC%A1%E7%9A%84%E9%94%99%E8%AF%AF%E6%98%AFhttps://update.scope-sentry.top/get/ksubdomain?system=linux&arch=amd64)" ksubdomain的，我的环境可以直接爬tiz。那我再等等吧，昨天的微信群满200了，还有没有其他的二维码，求一个。

嗷嗷 这俩是一样的 同样的操作 放到ext/ksubdomain/ksubdomain
![image](https://github.com/Autumn-27/ScopeSentry/assets/53844290/0c131b77-9be0-4201-aa86-78d497057cfb)

**Comment by a1most** [comment]
> > > > /apps/ext/rad/rad
> > > 
> > > 
> > > 已经放置了，并且chmod +x了，但是还是会23s自动重启
> > 
> > 
> > 看看日志报错
> 
> 还是这个错误，[2024-06-13 14:49:16] ERROR Error: Get "https://update.scope-sentry.top/get/ksubdomain?system=linux&arch=amd64": dial tcp: lookup update.scope-sentry.top on 127.0.0.11:53: read udp 127.0.0.1:46964->127.0.0.11:53: i/o timeout 2024-06-13 14:49:16 - [Error] SetUp Config Error

你看后面ksubdomain，这是另外一个工具，还要下载这个工具，然后和上面那个一样的操作。
