### ISSUE TITLE
关于节的点的探讨

### ISSUE THREAD

**Issue by york-cmd** [Autumn-27/ScopeSentry#63]
师傅 工具非常实用    节点是否可以通过web/服务端生成 配置文件和scan端直接在后台进行配置封装到一起, 下载二进制文件上线节点,这样的话多节点部署会很方便 不知道实现是否困难

**Comment by Autumn-27** [comment]
我考虑一下 主要是节点初始化需要一些配置

**Comment by Autumn-27** [comment]
但是好像和直接运行scan是一样的？ 只需要一份配置 节点名称为空的话会自动生成

**Comment by Autumn-27** [comment]
奥 你说的是不需要配置文件 直接整进程序里
