### ISSUE TITLE
单机部署报错depends_on相关问题

### ISSUE THREAD

**Issue by luoyang8848** [Autumn-27/ScopeSentry#64]
单机部署报错
ERROR: The Compose file './single-host-deployment.yml' is invalid because:
services.scope-sentry.depends_on contains an invalid type, it should be an array
services.scopesentry-scan.depends_on contains an invalid type, it should be an array

**Comment by dingafter** [comment]
depends_on多容器依赖启动，其中condition会用来检查依赖镜像的启动状态，检查下docker-compose,升级下
