### ISSUE TITLE
希望可以加入hunter、fofa等接口，能使用key来配合信息收集

### ISSUE THREAD

**Issue by jonezj** [Autumn-27/ScopeSentry#66]

**Comment by Autumn-27** [comment]
主要是哪个阶段呢？子域名？

**Comment by jonezj** [comment]
希望可以在资产测绘那边

**Comment by Autumn-27** [comment]
上线了一个fofa的插件https://plugin.scope-sentry.top/plugin/6fabcd0810be04c51aea034d99712213

其余的平台可以参考fofa写一个插件
