### ISSUE TITLE
.env中的密码和用户名更改后指纹信息识别不到，请问有没有什么解决办法呢

### ISSUE THREAD

**Issue by jonezj** [Autumn-27/ScopeSentry#67]

**Comment by jonezj** [comment]
就是指纹管理那边是空的

**Comment by jonezj** [comment]
<img width="1585" alt="6d923352921af8cb8a1e31c143c4ead" src="https://github.com/user-attachments/assets/d95d2995-96a5-442a-9886-2404083c740a">

**Comment by Autumn-27** [comment]
连上数据库，把ScopeSentry这个库删掉 然后重启一下server

**Comment by jonezj** [comment]
我将原始的用户名ScopeSentry改成了test就识别不到了

**Comment by jonezj** [comment]
好的我试下

**Comment by Autumn-27** [comment]
和用户名没有关系 这里没有数据 是初始化过程有问题

**Comment by jonezj** [comment]
好的，如果问题解决了我会及时回复您

**Comment by jonezj** [comment]
我这边没有按照您的方式重启数据库，而是重新启动了三次docker镜像自己好了，有点搞不明白
