### ISSUE TITLE
请问subfinder配置fofakey后怎么控制fofa查询数据的范围呢

### ISSUE THREAD

**Issue by jonezj** [Autumn-27/ScopeSentry#68]

**Comment by Autumn-27** [comment]
控制范围是指？

**Comment by jonezj** [comment]
就是一次查询多少页，一页多少条数据的控制，因为现在大部分是积分查询，有时候只需要查几百条不需要全部查询，全部查询会消耗大量积分造成不必要的浪费

**Comment by jonezj** [comment]
大佬我想问一下目录管理中txt文件中路径开头需要带/吗，还是说对于没有/开头的路径会自动添加/
