### ISSUE TITLE
节点空的，这个怎么添加呢 

### ISSUE THREAD

**Issue by 12tuz** [Autumn-27/ScopeSentry#7]
![image](https://github.com/Autumn-27/ScopeSentry/assets/113282242/014f4a4a-ced4-483f-939e-bb186eb9ced8)

**Comment by Autumn-27** [comment]
> ![image](https://private-user-images.githubusercontent.com/113282242/338681605-014f4a4a-ced4-483f-939e-bb186eb9ced8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTU5NTksIm5iZiI6MTcxODE1NTY1OSwicGF0aCI6Ii8xMTMyODIyNDIvMzM4NjgxNjA1LTAxNGY0YTRhLWNlZDQtNDgzZi05MzllLWJiMTg2ZWI5Y2VkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMTI3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjkyY2EzMGEyMTVjMWY2N2Y4ODQxMWJjY2I3YTQ2ZTM2NDI4OWFmYjQyNzJkNjdkZmE1NGEzYWQwOWQ3YWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yUjWrhp4guWlWZTp-z_pNXqcaW3J2qvaKEP2DFb4MAE)

运行scan
