### ISSUE TITLE
扫描任务中自带小迪吧希望可以去除

### ISSUE THREAD

**Issue by jonezj** [Autumn-27/ScopeSentry#70]
![1724857115400](https://github.com/user-attachments/assets/e88f0517-a09e-41a4-a79b-3b8f3f420e82)

**Comment by Autumn-27** [comment]
这是子域名跑出来的？

**Comment by jonezj** [comment]
> 这是子域名跑出来的？

不好意思我排查了一下原因是我随便上传字典把子域名给覆盖了。里面包含了小迪吧。实在不好意思
