### ISSUE TITLE
端口扫描BUG

### ISSUE THREAD

**Issue by XF-FS** [Autumn-27/ScopeSentry#73]
发现录入端口1-65535，，扫描的时候只能发现443端口，但使用默认的TOP1000，就可以发现其他端口，配置完重启过docker也无法生效。
![image](https://github.com/user-attachments/assets/bc3e266a-5a89-4f44-99a8-830110eb8132)
版本1.4
![image](https://github.com/user-attachments/assets/6ecbfd9b-3d23-4d1c-95e1-65e6b325234a)

**Comment by Autumn-27** [comment]
可以看下扫描节点有没有报错？是不是端口有一些其他字符导致失败了
![image](https://github.com/user-attachments/assets/93ddcdf2-a0b4-4cdd-ba6e-7e8d23c28dfa)
这是我自己测试的是成功的，这里我会在代码优化一下

**Comment by Sirocng** [comment]
我这里也是配置1-65535扫描出来的端口特别不全，希望扫描全端口的时候是把所有端口信息都记录下来的

**Comment by Autumn-27** [comment]
> 我这里也是配置1-65535扫描出来的端口特别不全，希望扫描全端口的时候是把所有端口信息都记录下来的

并发设置的是多少呢？ 所有端口信息是指？ 只要端口开放的应该是都会记录的，即使端口指纹没有识别到也会记录一个未知的值不会丢掉。目标方便发不？我测试测试

**Comment by Sirocng** [comment]
比如扫描ip：172.20.50.63全端口，我查看日志结果市识别到了全部开放端口：2024-09-25 10:49:01 - [INFO] 172.20.50.63 Port alive: 172.20.50.63 -> [135,139,445,902,912,2222,2701,3389,5040,5555,7680,7880,8005,8200,8226,8235,8276,9000,30012,30013,49664,49665,49666,49667,49668,49676,52019,53168,53169,53224]

但是返回总资产那里去查询，这个ip只能查到7条端口信息，它把一些端口省略掉了，我希望的是所有识别到的开放端口都能在资产那里查询到。一开始我是以为扫描出错，后来试了好几个ip，都是扫不全。

![01442be0cd5e411dbadeaa656920f93](https://github.com/user-attachments/assets/bbc85465-3747-4748-9abd-97a5585f521a)

**Comment by Autumn-27** [comment]
> 比如扫描ip：172.20.50.63全端口，我查看日志结果市识别到了全部开放端口：2024-09-25 10:49:01 - [INFO] 172.20.50.63 Port alive: 172.20.50.63 -> [135,139,445,902,912,2222,2701,3389,5040,5555,7680,7880,8005,8200,8226,8235,8276,9000,30012,30013,49664,49665,49666,49667,49668,49676,52019,53168,53169,53224]
> 
> 但是返回总资产那里去查询，这个ip只能查到7条端口信息，它把一些端口省略掉了，我希望的是所有识别到的开放端口都能在资产那里查询到。一开始我是以为扫描出错，后来试了好几个ip，都是扫不全。
> 
> ![01442be0cd5e411dbadeaa656920f93](https://private-user-images.githubusercontent.com/56618386/377054635-bbc85465-3747-4748-9abd-97a5585f521a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODMxODMsIm5iZiI6MTcyOTA4Mjg4MywicGF0aCI6Ii81NjYxODM4Ni8zNzcwNTQ2MzUtYmJjODU0NjUtMzc0Ny00NzQ4LTlhYmQtOTdhNTU4NWY1MjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEyNDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZjU1YTBhZmIwNDNkZDJlODFiNDM3MzgxNjcyMTkxYTc3ODRkNWU5NTdlOGZjNmNiODgyMzk1ZTgwMjg1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9S7tEmazvMeehpdF4iA6jezvUiHNlLUM-S5hEZewl7o)

好的，我测试一下，理论上来说 我代码上写了 只要开放就会记录下来，可能是有啥bug 我查一下

**Comment by Sirocng** [comment]
好的，我测试一下，理论上来说 我代码上写了 只要开放就会记录下来，可能是有啥bug 我查一下

从日志来看是能精准识别到所有开放端口，但是不能把识别的开放端口都扫描到，总资产里面能查询到

**Comment by Autumn-27** [comment]
> Re ：好的，我测试一下，理论上来说 我代码上写了 只要开放就会记录下来，可能是有啥bug 我查一下
> 
> 从日志来看是能精准识别到所有开放端口，但是不能把识别的开放端口都扫描到，总资产里面能查询到


现在在重构功能，下个版本会支持ip段、白名单等，全端口扫描这里刚刚看了下代码，可能是因为端口指纹没有识别出来，然后会用tcp连接获取原始输出，获取的过程出错了然后就忽略了这个端口，目前优化了一下，不会进行丢失了。并且之后支持插件化，如果内置的rustcan端口扫描不理想可以直接安装其他端口扫描的插件，所有的模块都可以插件化的安装工具。

**Comment by Sirocng** [comment]
> > Re ：好的，我测试一下，理论上来说 我代码上写了 只要开放就会记录下来，可能是有啥bug 我查一下
> > 从日志来看是能精准识别到所有开放端口，但是不能把识别的开放端口都扫描到，总资产里面能查询到
> 
> 现在在重构功能，下个版本会支持ip段、白名单等，全端口扫描这里刚刚看了下代码，可能是因为端口指纹没有识别出来，然后会用tcp连接获取原始输出，获取的过程出错了然后就忽略了这个端口，目前优化了一下，不会进行丢失了。并且之后支持插件化，如果内置的rustcan端口扫描不理想可以直接安装其他端口扫描的插件，所有的模块都可以插件化的安装工具。

大概什么时候推下个版本，很是期待
