### ISSUE TITLE
#建议添加站点识别

### ISSUE THREAD

**Issue by kw1001** [Autumn-27/ScopeSentry#74]
建议添加站点识别功能，可参考ARL。目前的资产识别和URL，跑出来太乱了

**Comment by Autumn-27** [comment]
可以详细说下~

**Comment by kw1001** [comment]
![Uploading 5b64a009101b922c818e7107bd93ed36.png…]()
这个是ARL任务下的WEB站点展示。
反观咱们的系统这边的站点展示太乱了，展示不够直观。
![image](https://github.com/user-attachments/assets/9ca8ef2a-4ad4-472e-b1ba-b6b22df7fd36)

**Comment by kw1001** [comment]
![42045dfe-1d9d-4b84-94d0-e20d864fb9f6](https://github.com/user-attachments/assets/87b1b2fe-2207-4441-baba-36f38d7a85e9)
这个是ARL任务下的WEB站点展示。
反观咱们的系统这边的站点展示太乱了，展示不够直观。
![8cb51631-b49f-4359-a162-86338da29218](https://github.com/user-attachments/assets/9eefa4c3-2155-4891-b334-55a540113cc7)

**Comment by Autumn-27** [comment]
为啥感觉并不是很乱？
灯塔的信息包括域名、标题、header、指纹、截图
ScopeSentry包括域名、ip、端口、标题、状态码、header、指纹
对我来说这些信息是我需要一眼看到的。 不过我在考虑支持自定义展示哪些数据

**Comment by Autumn-27** [comment]
还有侧边统计是灯塔没有的，但是侧边统计我认为在查找脆弱资产时可以更好的筛选

**Comment by kw1001** [comment]
我的建议是在栏目中添加一栏“URL”，http(s):////xxxxxx.com
同时这个任务的资产我是域名+IP，扫出来的结果与ARL对比。结果出来：基于IP的URL缺失很多。

**Comment by Autumn-27** [comment]
这里的url只是对比域名多了前缀，我在域名这里如果是http(s)的站点 在超链接的里边拼接了前缀，我可以调整一下在域名的地方直接显示http(s) 如果单独增加url数据有些重复。
基于ip的是这些ip的端口扫出来的端口比较少？还是说 原始的ip就没有识别出来网站呢？

**Comment by kw1001** [comment]
原始的ip就没有识别出来网站

**Comment by Autumn-27** [comment]
灯塔和ScopeSentry是部署在一个平台吗？ 感觉原始数据的话应该不会出现问题 因为是直接调用httpx进行访问的

**Comment by kw1001** [comment]
是分开两台服务器部署的

**Comment by Autumn-27** [comment]
是否可以测试 在ScopeSentry上是否能访问丢失的ip
大概量级是多少呀？我再看看代码 看哪里是否会丢失一些数据

**Comment by kw1001** [comment]
能正常访问。大部分原始的ip都没有识别出来网站

**Comment by Autumn-27** [comment]
能给个测试样例不 我测试一下

**Comment by kw1001** [comment]
这不太方便，因为是在做授权内的资产绘测

**Comment by kw1001** [comment]
我刚刚清除所有数据，重新建立了一个任务，资产只有IP，这一次的站点识别就正常了。
估计之前是因为资产里面填写了IP+域名，从而影响了站点识别的结果
