### ISSUE TITLE
扫描的时候 报错 日志显示这个

### ISSUE THREAD

**Issue by liangyao1** [Autumn-27/ScopeSentry#79]
2024-10-23 17:45:21 - [INFO] Get a new task~
2024-10-23 17:45:21 - [ERROR] Task parse error: %!s(<nil>)

**Comment by Autumn-27** [comment]
能看下任务配置不？

**Comment by liangyao1** [comment]
就是项目管理里的那些项目，有一些自带url的，开启运行一次就报了这个错误

**Comment by liangyao1** [comment]
> 能看下任务配置不？

就是项目管理里的那些项目，有一些自带url的，开启运行一次就报了这个错误

**Comment by Autumn-27** [comment]
> > 能看下任务配置不？
> 
> 
> 
> 就是项目管理里的那些项目，有一些自带url的，开启运行一次就报了这个错误

不知道你这个具体是啥情况 之前没碰到过这种报错 触发了隐藏bug  下个版本任务这块会重构一下 应该不会有这个问题
