### ISSUE TITLE
运行scan后，卡住不动

### ISSUE THREAD

**Issue by cherichm** [Autumn-27/ScopeSentry#8]
![image](https://github.com/Autumn-27/ScopeSentry/assets/46641497/5b2c828c-5152-4e1e-b759-25c18d7b2e4a)

**Comment by Autumn-27** [comment]
> ![image](https://private-user-images.githubusercontent.com/46641497/338792708-5b2c828c-5152-4e1e-b759-25c18d7b2e4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTY0MzYsIm5iZiI6MTcxODE1NjEzNiwicGF0aCI6Ii80NjY0MTQ5Ny8zMzg3OTI3MDgtNWIyYzgyOGMtNTE1Mi00ZTFlLWI3NTktMjVjMThkN2IyZTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAxMzUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NGZhN2YzZDA1MmQxNGExZTk0YTIwNDcyM2U3ZGMxNjZiYWFjNzI3MTRlOWM1ZmJjOGY1ZGI3NjkyNDkzOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H4cD0DHsbdIBnNzliUJ8rdZAmoU6Bo9lHHeWbXqaLcM)

这是在加载数据库中的数据，可以抓包看一下是否还在加载，有时候网络不好的话可能会比较久
