### ISSUE TITLE
scopesentry-scan容器启动失败

### ISSUE THREAD

**Issue by happy-wyq** [Autumn-27/ScopeSentry#89]
![image](https://github.com/user-attachments/assets/84dd07d1-875a-474b-9fed-c42f52ad621c)

**Comment by Autumn-27** [comment]
https://github.com/Autumn-27/ScopeSentry/issues/11

**Comment by Autumn-27** [comment]
晚些我修复一下不让一直重启 具体应该是ksubdomain没获取到网卡
