### ISSUE TITLE
用docker安装，scope-sentry的容器状态会是unhealth，看日志报错如下

### ISSUE THREAD

**Issue by xingyunliuyue** [Autumn-27/ScopeSentry#90]
2024-11-25 10:59:08.863 | ERROR    | core.db:create_database:187 - Error creating database: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}

这是需要啥权限？

**Comment by Autumn-27** [comment]
认证错误检测步骤：
1. 单机部署确保.env填写正确
2. 单机部署下如果之前搭建过，看下是不是项目目录下的data文件夹是否没有删除，如果没有删除，数据库会挂载到这个目录，会导致密码是之前的。

**Comment by xingyunliuyue** [comment]
之前搭建过的，我是升级的时候将保留原来的.env和数据库的东西，将scope-sentry和scan镜像删除了，重新拉取，但是报错

**Comment by Autumn-27** [comment]
> 之前搭建过的，我是升级的时候将保留原来的.env和数据库的东西，将scope-sentry和scan镜像删除了，重新拉取，但是报错 试过用新的docker-compose.yml文件运行还是有这个错误 报错如下 ![image](https://private-user-images.githubusercontent.com/65636727/389391559-eec39a25-a90e-4f00-a944-ee0cc4726e83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTY2MzUsIm5iZiI6MTczMjUxNjMzNSwicGF0aCI6Ii82NTYzNjcyNy8zODkzOTE1NTktZWVjMzlhMjUtYTkwZS00ZjAwLWE5NDQtZWUwY2M0NzI2ZTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA2MzIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YmFmNmVhZWQ1N2JhMGIxNTg4NjAxMWI5ZTlmZDVhYzYwMjc5M2E2YTcxZmM2NDkwMTk4ODc5OTI4NmM2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NlrvNArqhUTdQ7yW2I-i4WiTSvFxKTLgVh-G_tmTMXs)

可以进mongodb容器里边看下密码是啥 在环境变量里边 试试里边那个密码是否可以连接

**Comment by xingyunliuyue** [comment]
环境变量在哪个位置

**Comment by Autumn-27** [comment]
> 环境变量在哪个位置 之前设置的数据库用户名是scoposentry，我看新版现在都是admin,跟这个有关系？

数据库都是自己设置的 我配置里的只是默认的demo 如果找不到密码的话 建议整个ScopeSentry目录全部删除 重新搭建

**Comment by xingyunliuyue** [comment]
好吧
